# This is a basic workflow to help you get started with Actions

name: Push_To_Azure_CR

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# First job to build and push commit tage image to CR
jobs:
  # This workflow contains a single job called "build_commit_docker"
  build_commit_docker:
    name: 'Build commit tag for CR'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Login to azure CLI
      - name: Build and push image
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      # Build and push the docker image to the container
      - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/keycloak-operator:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/keycloak-operator:${{ github.sha }}
  # This workflow contains a single job called "build_latest_tag"
  build_latest_tag:
    name: 'Build commit tag for CR'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Login to azure CLI
      - name: Build and push image
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      # Build and push the docker image to the container
      - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/keycloak-operator:latest
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/keycloak-operator:latest
